# syntax=docker/dockerfile:1
FROM sirkkalap/oraclelinux-systemd
ENV SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt \
    CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
RUN --mount=type=secret,id=custom_root_ca,target=/run/secrets/custom-root-ca \
    if [ -s /run/secrets/custom-root-ca ]; then \
      cp /run/secrets/custom-root-ca /etc/pki/ca-trust/source/anchors/custom-root-ca.crt; \
      update-ca-trust; \
    fi


RUN yum update -y
RUN yum install iproute -y
RUN yum install sudo -y
RUN yum install python3 -y
RUN yum reinstall ca-certificates -y
RUN yum install openssh-clients -y
RUN yum install openssl -y
RUN yum install openssh-server -y
RUN yum install which -y
