# syntax=docker/dockerfile:1

FROM jrei/systemd-centos:8
ARG CUSTOM_CA_CERT_BASE64=""
ENV SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt \
    CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
RUN if [ -n "${CUSTOM_CA_CERT_BASE64}" ]; then \
      printf "%s" "${CUSTOM_CA_CERT_BASE64}" | base64 -d > /etc/pki/ca-trust/source/anchors/custom-root-ca.crt; \
      update-ca-trust; \
    fi


RUN sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*
RUN sed -i -e "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*

RUN yum install iproute -y
RUN yum install sudo -y
RUN yum install python3 -y
RUN yum install ca-certificates -y
RUN yum install openssh-clients -y
RUN yum install openssl -y
RUN yum install openssh-server -y
RUN yum install which -y
