# syntax=docker/dockerfile:1

FROM almalinux:8.7
ENV SSL_CERT_FILE=/etc/pki/tls/certs/ca-bundle.crt \
    CURL_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt \
    REQUESTS_CA_BUNDLE=/etc/pki/tls/certs/ca-bundle.crt
RUN --mount=type=secret,id=custom_root_ca,target=/run/secrets/custom-root-ca \
    if [ -s /run/secrets/custom-root-ca ]; then \
      cp /run/secrets/custom-root-ca /etc/pki/ca-trust/source/anchors/custom-root-ca.crt; \
      update-ca-trust; \
    fi

RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN dnf install glibc-langpack-en -y
RUN dnf -qy module disable postgresql -y
RUN dnf update -y
RUN dnf install sudo -y
RUN dnf install python3 -y
RUN dnf install ca-certificates -y
RUN dnf install openssh-clients -y
RUN dnf install openssh-server -y
RUN dnf install which -y
# fix issue detecting ip investigate why this is not needed in rockylinux
RUN dnf install iproute -y
