# syntax=docker/dockerfile:1

FROM jrei/systemd-debian:11
ARG CUSTOM_CA_CERT_BASE64=""
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt \
    CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
    REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt \
    PIP_CERT=/etc/ssl/certs/ca-certificates.crt
RUN if [ -n "${CUSTOM_CA_CERT_BASE64}" ]; then \
      printf "%s" "${CUSTOM_CA_CERT_BASE64}" | base64 -d > /usr/local/share/ca-certificates/custom-root-ca.crt; \
      update-ca-certificates; \
    fi


RUN apt update
RUN apt install sudo -y
RUN apt install python3 -y
RUN apt install ca-certificates -y
RUN apt install openssh-client -y
RUN apt install openssh-server -y
RUN apt install python3-apt -y
RUN apt install gpg -y
RUN apt install acl -y
RUN apt install apt-transport-https -y
RUN apt-get update -y
RUN apt-get install iproute2 -y
RUN apt-get install software-properties-common -y
RUN apt-add-repository 'deb http://archive.debian.org/debian-security stretch/updates main' -y
RUN apt-get update -y
RUN apt-get install openjdk-8-jdk -y
RUN systemctl disable ssh
