# syntax=docker/dockerfile:1

FROM opensuse/leap:latest
ARG CUSTOM_CA_CERT_BASE64=""
ENV SSL_CERT_FILE=/etc/ssl/ca-bundle.pem \
    CURL_CA_BUNDLE=/etc/ssl/ca-bundle.pem \
    REQUESTS_CA_BUNDLE=/etc/ssl/ca-bundle.pem
RUN if [ -n "${CUSTOM_CA_CERT_BASE64}" ]; then \
      printf "%s" "${CUSTOM_CA_CERT_BASE64}" | base64 -d > /usr/share/pki/trust/anchors/custom-root-ca.crt; \
      update-ca-certificates; \
    fi


RUN zypper -n install systemd
RUN zypper clean
RUN zypper update
RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
systemd-tmpfiles-setup.service ] || rm -f $i; done); \
rm -f /lib/systemd/system/multi-user.target.wants/*;\
rm -f /etc/systemd/system/*.wants/*;\
rm -f /lib/systemd/system/local-fs.target.wants/*; \
rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
rm -f /lib/systemd/system/basic.target.wants/*;\
rm -f /lib/systemd/system/anaconda.target.wants/*;
RUN zypper install --no-confirm openssh
RUN zypper install --no-confirm sudo
RUN zypper install --no-confirm iproute2
RUN zypper install --no-confirm python3
