include ../../Makefile.mk

build-centos7:
	$(COMPOSE) up primary1-centos7 -d
	$(COMPOSE) up standby1-centos7 -d
	$(COMPOSE) up standby2-centos7 -d

build-rocky8:
	$(COMPOSE) up primary1-rocky8 -d
	$(COMPOSE) up standby1-rocky8 -d
	$(COMPOSE) up standby2-rocky8 -d

build-rocky9:
	$(COMPOSE) up primary1-rocky9 -d
	$(COMPOSE) up standby1-rocky9 -d
	$(COMPOSE) up standby2-rocky9 -d

build-almalinux8:
	$(COMPOSE) up primary1-almalinux8 -d
	$(COMPOSE) up standby1-almalinux8 -d
	$(COMPOSE) up standby2-almalinux8 -d

build-debian9:
	$(COMPOSE) up primary1-debian9 -d
	$(COMPOSE) up standby1-debian9 -d
	$(COMPOSE) up standby2-debian9 -d

build-debian10:
	$(COMPOSE) up primary1-debian10 -d
	$(COMPOSE) up standby1-debian10 -d
	$(COMPOSE) up standby2-debian10 -d

build-ubuntu20:
	$(COMPOSE) up primary1-ubuntu20 -d
	$(COMPOSE) up standby1-ubuntu20 -d
	$(COMPOSE) up standby2-ubuntu20 -d

build-oraclelinux7:
	$(COMPOSE) up primary1-oraclelinux7 -d
	$(COMPOSE) up standby1-oraclelinux7 -d
	$(COMPOSE) up standby2-oraclelinux7 -d
